

名字: ji_maotai
on:
  release:v0.0.1
    types: [created
   workflow_dispatch: # 手动触发
    schedule: # 计划任务触发
    - cron: '0 16 * * *' 


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
      run: |
        python main.py
