

name: ji_maotai
on:


   workflow_dispatch: # 手动触发
    schedule: # 计划任务触发
    - cron: '0 16 * * *' 


jobs:
 run-jd-maotai-seckill:
 
    runs-on: ubuntu-latest
    

    steps:

    # 输出IP
    - name: IP
      run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        
    - name: run app
      run: |
        python ./main.py
